## read the fines.csv that you saved

In [1]:
import pandas as pd
import gc
df = pd.read_csv('../../data/fines.csv')
df

        CarNumber  Refund   Fines    Make     Model  Year
0    Y163O8161RUS       2  3200.0    Ford     Focus  1989
1     E432XX77RUS       1  6500.0  Toyota     Camry  1995
2     7184TT36RUS       1  2100.0    Ford     Focus  1984
3    X582HE161RUS       2  2000.0    Ford     Focus  2015
4    92918M178RUS       1  5700.0    Ford     Focus  2014
..            ...     ...     ...     ...       ...   ...
925  K492MX777RUS       2  1000.0    Ford    Bronco  2019
926  A815BC199RUS       1  2000.0  Subaru    Legacy  2020
927  M307ET161RUS       2  3000.0     Kia  Sportage  2019
928  X554OH750RUS       1  4000.0    Ford  Explorer  2020
929  P921KA123RUS       2  5000.0  Toyota    Tacoma  2019

[930 rows x 6 columns]

In [2]:
%%timeit
calculated = []
for i in range(0, len(df)):
    res = df.iloc[i]['Fines'] / df.iloc[i]['Refund'] * df.iloc[i]['Year']
    calculated.append(res)
df['Calculated'] = calculated

102 ms ± 394 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [3]:
df

        CarNumber  Refund   Fines    Make     Model  Year  Calculated
0    Y163O8161RUS       2  3200.0    Ford     Focus  1989   3182400.0
1     E432XX77RUS       1  6500.0  Toyota     Camry  1995  12967500.0
2     7184TT36RUS       1  2100.0    Ford     Focus  1984   4166400.0
3    X582HE161RUS       2  2000.0    Ford     Focus  2015   2015000.0
4    92918M178RUS       1  5700.0    Ford     Focus  2014  11479800.0
..            ...     ...     ...     ...       ...   ...         ...
925  K492MX777RUS       2  1000.0    Ford    Bronco  2019   1009500.0
926  A815BC199RUS       1  2000.0  Subaru    Legacy  2020   4040000.0
927  M307ET161RUS       2  3000.0     Kia  Sportage  2019   3028500.0
928  X554OH750RUS       1  4000.0    Ford  Explorer  2020   8080000.0
929  P921KA123RUS       2  5000.0  Toyota    Tacoma  2019   5047500.0

[930 rows x 7 columns]

In [4]:
%%timeit
calculated = []
for _, row in df.iterrows():
    res = row['Fines'] / row['Refund'] * row['Year']
    calculated.append(res)
df['Calculated'] = calculated

36.6 ms ± 48.2 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [5]:
df

        CarNumber  Refund   Fines    Make     Model  Year  Calculated
0    Y163O8161RUS       2  3200.0    Ford     Focus  1989   3182400.0
1     E432XX77RUS       1  6500.0  Toyota     Camry  1995  12967500.0
2     7184TT36RUS       1  2100.0    Ford     Focus  1984   4166400.0
3    X582HE161RUS       2  2000.0    Ford     Focus  2015   2015000.0
4    92918M178RUS       1  5700.0    Ford     Focus  2014  11479800.0
..            ...     ...     ...     ...       ...   ...         ...
925  K492MX777RUS       2  1000.0    Ford    Bronco  2019   1009500.0
926  A815BC199RUS       1  2000.0  Subaru    Legacy  2020   4040000.0
927  M307ET161RUS       2  3000.0     Kia  Sportage  2019   3028500.0
928  X554OH750RUS       1  4000.0    Ford  Explorer  2020   8080000.0
929  P921KA123RUS       2  5000.0  Toyota    Tacoma  2019   5047500.0

[930 rows x 7 columns]

In [6]:
%%timeit
df["Calculated"] = df.apply(lambda r: r["Fines"] * r["Year"] / r["Refund"],axis=1)

7.83 ms ± 61.4 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [7]:
df

        CarNumber  Refund   Fines    Make     Model  Year  Calculated
0    Y163O8161RUS       2  3200.0    Ford     Focus  1989   3182400.0
1     E432XX77RUS       1  6500.0  Toyota     Camry  1995  12967500.0
2     7184TT36RUS       1  2100.0    Ford     Focus  1984   4166400.0
3    X582HE161RUS       2  2000.0    Ford     Focus  2015   2015000.0
4    92918M178RUS       1  5700.0    Ford     Focus  2014  11479800.0
..            ...     ...     ...     ...       ...   ...         ...
925  K492MX777RUS       2  1000.0    Ford    Bronco  2019   1009500.0
926  A815BC199RUS       1  2000.0  Subaru    Legacy  2020   4040000.0
927  M307ET161RUS       2  3000.0     Kia  Sportage  2019   3028500.0
928  X554OH750RUS       1  4000.0    Ford  Explorer  2020   8080000.0
929  P921KA123RUS       2  5000.0  Toyota    Tacoma  2019   5047500.0

[930 rows x 7 columns]

In [8]:
%%timeit
df['Calcualted'] = df['Fines'] / df['Refund'] * df['Year']

194 μs ± 11.3 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [9]:
%%timeit
df['Calcualted'] = df['Fines'].values / df['Refund'].values * df['Year'].values

93.9 μs ± 2.04 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

## indexing: measure the time using the magic command %%timeit in the cell

In [10]:
%%timeit
row = df[df['CarNumber'] == 'O136HO197RUS']

252 μs ± 3.29 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [11]:
df.set_index('CarNumber')

              Refund   Fines    Make     Model  Year  Calculated  Calcualted
CarNumber
Y163O8161RUS       2  3200.0    Ford     Focus  1989   3182400.0   3182400.0
E432XX77RUS        1  6500.0  Toyota     Camry  1995  12967500.0  12967500.0
7184TT36RUS        1  2100.0    Ford     Focus  1984   4166400.0   4166400.0
X582HE161RUS       2  2000.0    Ford     Focus  2015   2015000.0   2015000.0
92918M178RUS       1  5700.0    Ford     Focus  2014  11479800.0  11479800.0
...              ...     ...     ...       ...   ...         ...         ...
K492MX777RUS       2  1000.0    Ford    Bronco  2019   1009500.0   1009500.0
A815BC199RUS       1  2000.0  Subaru    Legacy  2020   4040000.0   4040000.0
M307ET161RUS       2  3000.0     Kia  Sportage  2019   3028500.0   3028500.0
X554OH750RUS       1  4000.0    Ford  Explorer  2020   8080000.0   8080000.0
P921KA123RUS       2  5000.0  Toyota    Tacoma  2019   5047500.0   5047500.0

[930 rows x 7 columns]

In [12]:
%%timeit
better_row = df[df.index == 'O136HO197RUS']

129 μs ± 8.06 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

## downcasting

In [13]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CarNumber   930 non-null    object
 1   Refund      930 non-null    int64
 2   Fines       930 non-null    float64
 3   Make        930 non-null    object
 4   Model       919 non-null    object
 5   Year        930 non-null    int64
 6   Calculated  930 non-null    float64
 7   Calcualted  930 non-null    float64
dtypes: float64(3), int64(2), object(3)
memory usage: 189.4 KB

In [14]:
optimized = df.copy()
optimized[optimized.select_dtypes(include='float64').columns] = optimized[optimized.select_dtypes(include='float64').columns].astype('float32')

In [15]:
optimized = optimized.astype({
    "CarNumber": "category",
    "Refund": "int8",
    "Make": "category",
    "Model": "category",
    "Year": "int16",
})

In [16]:
optimized.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CarNumber   930 non-null    category
 1   Refund      930 non-null    int8
 2   Fines       930 non-null    float32
 3   Make        930 non-null    category
 4   Model       919 non-null    category
 5   Year        930 non-null    int16
 6   Calculated  930 non-null    float32
 7   Calcualted  930 non-null    float32
dtypes: category(3), float32(3), int16(1), int8(1)
memory usage: 67.5 KB

## memory clean

In [17]:
gc.collect()
%reset_selective df

In [18]:
df

NameError: name 'df' is not defined