## create a connection to the database using the library sqlite3

In [1]:
import pandas as pd
import sqlite3
connection = sqlite3.connect('../../data/checking-logs.sqlite')
pd.io.sql.read_sql("PRAGMA table_info(pageviews);", connection)

   cid      name       type  notnull dflt_value  pk
0    0     index    INTEGER        0       None   0
1    1       uid       TEXT        0       None   0
2    2  datetime  TIMESTAMP        0       None   0

## get only the first 10 rows of the table pageviews

In [2]:
pd.io.sql.read_sql('SELECT * FROM pageviews LIMIT 10;', connection)

   index      uid                    datetime
0      0  admin_1  2020-04-17 12:01:08.463179
1      1  admin_1  2020-04-17 12:01:23.743946
2      2  admin_3  2020-04-17 12:17:39.287778
3      3  admin_3  2020-04-17 12:17:40.001768
4      4  admin_1  2020-04-17 12:27:30.646665
5      5  admin_1  2020-04-17 12:35:44.884757
6      6  admin_1  2020-04-17 12:35:52.735016
7      7  admin_3  2020-04-17 12:36:21.401412
8      8  admin_3  2020-04-17 12:36:22.023355
9      9  admin_1  2020-04-17 13:55:19.129243

## get the subtable using only one query

In [3]:
##only uid and datetime are used
pd.io.sql.read_sql("SELECT uid, datetime FROM pageviews LIMIT 10;", connection)

       uid                    datetime
0  admin_1  2020-04-17 12:01:08.463179
1  admin_1  2020-04-17 12:01:23.743946
2  admin_3  2020-04-17 12:17:39.287778
3  admin_3  2020-04-17 12:17:40.001768
4  admin_1  2020-04-17 12:27:30.646665
5  admin_1  2020-04-17 12:35:44.884757
6  admin_1  2020-04-17 12:35:52.735016
7  admin_3  2020-04-17 12:36:21.401412
8  admin_3  2020-04-17 12:36:22.023355
9  admin_1  2020-04-17 13:55:19.129243

In [4]:
query = '''
SELECT uid, datetime FROM pageviews
WHERE uid LIKE 'user_%'
ORDER BY uid;
'''
pageviews = pd.read_sql(query, connection)
pageviews["datetime"] = pd.to_datetime(pageviews["datetime"])
pageviews = pageviews.set_index('datetime')

In [5]:
pageviews.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 987 entries, 2020-04-26 21:53:59.624136 to 2020-05-21 16:36:40.915488
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   uid     987 non-null    object
dtypes: object(1)
memory usage: 15.4+ KB

## close the connection to the database

In [6]:
connection.close()